In [1]:
import pandas as pd
import time
import numpy as np
from sklearn.cross_validation import train_test_split
import lightgbm as lgb
import gc
import matplotlib.pyplot as plt
import os
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from scipy.special import expit, logit
from sklearn.metrics import roc_auc_score

almost_zero = 1e-10
almost_one = 1 - almost_zero


traininfo = [['./sub_dart_train_BayesOpt_2018_0501_0125_11.csv', './sub_dart_train_BayesOpt_2018_0501_0315_38.csv',
              './sub_dart_train_BayesOpt_2018_0501_0518_48.csv', './sub_dart_train_BayesOpt_2018_0501_0715_06.csv'],
             ['./sub_xgdt_train_BayesOpt_2018_0430_1519_33.csv', './sub_xgdt_train_BayesOpt_2018_0430_1656_17.csv', 
              './sub_xgdt_train_BayesOpt_2018_0430_1844_31.csv', './sub_xgdt_train_BayesOpt_2018_0430_2026_42.csv']
            ]

validinfo = [['./sub_dart_valid_BayesOpt_2018_0501_0125_11.csv', './sub_dart_valid_BayesOpt_2018_0501_0315_38.csv',
              './sub_dart_valid_BayesOpt_2018_0501_0518_48.csv', './sub_dart_valid_BayesOpt_2018_0501_0715_06.csv'],
             ['./sub_xgdt_valid_BayesOpt_2018_0430_1519_33.csv', './sub_xgdt_valid_BayesOpt_2018_0430_1656_17.csv', 
              './sub_xgdt_valid_BayesOpt_2018_0430_1844_31.csv', './sub_xgdt_valid_BayesOpt_2018_0430_2026_42.csv']
            ]

testinfo = [['./sub_dart_BayesOpt_2018_0501_0148_24.csv', './sub_dart_BayesOpt_2018_0501_0339_24.csv',
             './sub_dart_BayesOpt_2018_0501_0544_49.csv', './sub_dart_BayesOpt_2018_0501_0739_43.csv'],
            ['./sub_it_BayesOpt_2018_0430_1527_02.csv', './sub_it_BayesOpt_2018_0430_1703_36.csv',
             './sub_it_BayesOpt_2018_0430_1854_57.csv', './sub_it_BayesOpt_2018_0430_2035_07.csv']]

train_trueinfo = [['./rawdata_train_From2400_2018_0501_0125_11.csv', './rawdata_train_From2400_2018_0501_0315_38.csv',
                   './rawdata_train_From2400_2018_0501_0518_48.csv', './rawdata_train_From2400_2018_0501_0715_06.csv'],
                  ['./rawdata_valid_From2400_2018_0501_0125_11.csv', './rawdata_valid_From2400_2018_0501_0315_38.csv',
                   './rawdata_valid_From2400_2018_0501_0518_48.csv', './rawdata_valid_From2400_2018_0501_0715_06.csv']
                 ]
                  
validlen = 5000000
models = []
data = pd.read_csv(train_trueinfo[0][0], nrows=10)
data

C:\Users\ahega\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

,app,channel,click_id,click_time,device,ip,is_attributed,os,hour,day,...,nextClick_shift,nextClick_shift_shift,nextClick_shiftback,ip_tcount,ip_app_count,ip_app_os_count,ip_tchan_count,ip_app_os_var,ip_app_channel_var_day,ip_app_channel_mean_hour
0,3,417,NaN,2017-11-07 04:24:44,1,55464,0.0,13,4,7,...,NaN,NaN,0.0,103,134,41,4.166667,10.998780,0.000000,8.166667
1,12,178,NaN,2017-11-07 04:24:44,1,143615,0.0,20,4,7,...,4.0,NaN,20368.0,25,46,8,15.776667,7.071429,0.000000,10.120000
2,2,212,NaN,2017-11-07 04:24:44,1,34075,0.0,16,4,7,...,0.0,4.0,9342.0,35,142,3,7.102564,25.333333,1.472727,9.000000
3,11,325,NaN,2017-11-07 04:24:44,1,199423,0.0,16,4,7,...,20368.0,0.0,1.0,61,16,2,7.000000,4.500000,0.000000,6.000000
4,9,232,NaN,2017-11-07 04:24:44,1,58891,0.0,19,4,7,...,9342.0,20368.0,3525.0,95,124,23,16.952381,14.810277,2.290909,7.636364
5,2,122,NaN,2017-11-07 04:24:44,1,159413,0.0,19,4,7,...,1.0,9342.0,5173.0,8,5,3,NaN,0.333333,NaN,4.000000
6,2,469,NaN,2017-11-07 04:24:44,1,64345,0.0,17,4,7,...,3525.0,1.0,55.0,88,232,17,18.105263,16.382353,2.286290,9.125000
7,9,215,NaN,2017-11-07 04:24:44,1,156022,0.0,19,4,7,...,5173.0,3525.0,61.0,48,12,8,NaN,12.500000,NaN,4.000000
8,15,412,NaN,2017-11-07 04:24:44,1,160555,0.0,13,4,7,...,55.0,5173.0,13.0,17,15,3,NaN,27.000000,NaN,4.000000
9,8,259,NaN,2017-11-07 04:24:44,1,55776,0.0,30,4,7,...,61.0,55.0,4.0,74,65,4,16.011477,0.000000,2.118462,9.346154